Style/MethodCallParentheses:
  Enabled: false
  Description: 'Do not use parentheses for method calls with no arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-args-no-parens'

Style/BracesAroundHashParameters:
  Enabled: false
  EnforcedStyle: no_braces
  SupportedStyles:
  # The `braces` style enforces braces around all method parameters that are
  # hashes.
  - braces
  # The `no_braces` style checks that the last parameter doesn't have braces
  # around it.
  - no_braces
  # The `context_dependent` style checks that the last parameter doesn't have
  # braces around it, but requires braces if the second to last parameter is
  # also a hash literal.
  - context_dependent

Style/CommentAnnotation:
  Description: >-
    Checks formatting of special comments
    (TODO, FIXME, OPTIMIZE, HACK, REVIEW).
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#annotate-keywords'
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Metrics/LineLength:
  Enabled: false





