welcome_message: >-
  Welcome to the Battleship game Commander! In this game, the objective is to find and destory all the opposing commanders ships.


  Each commander will be given a turn to pick a coordinate to which to send missiles to hit the enemy ships. After every move, the corresponding representation of the battlefield will be updated with the appropriate mark. Coordinates are entered by entering two numbers separated by a comma (i.e. 5,2 or 5, 2). Thee first number represent the row, the second the column.


  'x' Marks a hit

  '/' Marks a miss


  A commander will have won the game if all the opposing enemy ships are sunk. The status of the commander is represented by their hitpoints. Once this reaches zero, it means that all ships have been sunk!


  As a commander you have the RIGHT to position your ships. However, if you also choose to do so you may delegate this taks to your strategist.


  That is all for now commander! Good luck!

landscape_error: >-
  Sorry commander, but the current landscape cannot fit the battlefield that you selected. Please make sure that landscape is at least the ff:


  * 34 rows for skirmish

  * 48 rows for battlezone

  * 57 rows for warzone.


  Adjust the landscape size or choose a smaller battlefield.

ships:
  destroyer:
    length: 1
    width: 1

  cruiser:
    length: 1
    width: 2

  battleship:
    length: 1
    width: 3

  carrier:
    length: 2
    width: 4

num_ships: 5

dimension: 7

ships_composition:
  - cruiser
  - battleship
  - destroyer
  - carrier
  - battleship

max_random_tries: 5000