ships:
  destroyer:
    length: 1
    width: 1

  cruiser:
    length: 1
    width: 2

  battleship:
    length: 1
    width: 3

  carrier:
    length: 2
    width: 4

max_ships: 3

ships_composition:
  - destroyer
  - cruiser
  - battleship